### PR TITLE
BUG: fixes typo

### PR DESCRIPTION
**Pull request by tpberntsen**

### CODE REVIEW

**Review by dburgener — APPROVED** [review]

**Comment by pcmoore** [comment]
Hi @tpberntsen, thanks for the PR!  Would you mind signing the commit as described in the CONTRIBUTING docs?

https://github.com/SELinuxProject/selinux-notebook/blob/main/CONTRIBUTING.md#sign-your-work

**Comment by dburgener** [comment]
refpolicy uses [this](https://probot.github.io/apps/dco/) github extension to check for proper signoffs.  @pcmoore what would your thoughts be about using it here?

**Comment by pcmoore** [comment]
> refpolicy uses [this](https://probot.github.io/apps/dco/) github extension to check for proper signoffs. @pcmoore what would your thoughts be about using it here?

Good idea, I use this on other repos too with good effect.  I just enabled it for this repository, but my guess is it will only apply to new PRs.

**Comment by pcmoore** [comment]
A patch based on @tpberntsen's original problem report has been merged via 9a24f75e709216cb56188b4650b2f7081c0cc2a3, thanks everyone!

**Pull request closed without merging**
