### PR TITLE
MAINTAINER_PROCESS: add an initial guidance doc for maintainers

### PR DESCRIPTION
**Pull request by pcmoore**
@jbrindle, @jwcart2, @dburgener please take a look and let me know if this seems reasonable and if you think we should change anything.

### CODE REVIEW

**Comment by dburgener** [comment]
This seems fine to me.  My only comment is that if we are going to have four maintainers right now, then "simple majority", means "3/4", which might be a fairly high bar (particularly since we're in this discussion due to lack of maintainer/reviewer time).  I might be inclined to emphasize the "no NACKs and a reasonable amount of time" sort of workflow, and to change "majority" something that means two maintainers is sufficient.

**Comment by stephensmalley** [comment]
> This seems fine to me. My only comment is that if we are going to have four maintainers right now, then "simple majority", means "3/4", which might be a fairly high bar (particularly since we're in this discussion due to lack of maintainer/reviewer time). I might be inclined to emphasize the "no NACKs and a reasonable amount of time" sort of workflow, and to change "majority" something that means two maintainers is sufficient.

Concur - this seems more consistent with how the SELinux userspace maintenance process works; IIRC we only require that at least one maintainer other than the patch author ACK the patch and no maintainers NAK or request changes to it. BTW I am also willing to help with the notebook.

**Comment by pcmoore** [comment]
That's good feedback, thanks @dburgener and @stephensmalley.  I've updated the doc, let me know if this works better for you guys.

**Comment by pcmoore** [comment]
> BTW I am also willing to help with the notebook.

Thanks Stephen.  It looks like you should already be setup with the proper permissions, if you notice anything awry let me know.

**Review by dburgener — APPROVED** [review]

**Comment by dburgener** [comment]
Acked-by: Daniel Burgener <dburgener@linux.microsoft.com>

**Comment by pcmoore** [comment]
Okay, let's go ahead and merge this so we've got *something* in place, we can always update later if needed.  Thanks all.

Merged via a7ef8dfd72689096574f5967ef383244a69dedb3.

**Pull request closed without merging**
